cool pre commit hook

diff --git a/.development/pre-commit-hook b/.development/pre-commit-hook
--- a/.development/pre-commit-hook
+++ b/.development/pre-commit-hook
@@ -1,36 +1,18 @@
 #!/bin/bash
-printf 'Looking for errors on the client...'
-ERRORS_ON_CLIENT=`find app/client -name '*.js' | xargs jshint`
-if [ "$?" != "0" ]; then
-    printf '\033[1;31m \xe2\x9c\x98\n\033[0m'; # failed
-    echo
-    echo "output below:\n"
-    echo $ERRORS_ON_CLIENT
-    exit 1
-else
+for kind in "client server terminal"; do
+printf "Looking for errors on the $kind..."
+find app/$kind -name '*.js' | xargs jshint 2>&1>/dev/null
+if [ "$?" == "0" ]; then
     printf '\033[1;32m \xe2\x9c\x94\n\033[0m'; # passed
+else
+    printf '\033[1;31m \xe2\x9c\x98\n\033[0m'; # failed
+    find app/$kind -name '*.js' | xargs jshint # I know it is stupid
+                                                # to run again, but it
+                                                # happens that I wanna
+                                                # show the pretty
+                                                # unicode chars before
+                                                # that
+    exit 1
 fi;
 
-printf 'Looking for errors on the server...'
-ERRORS_ON_SERVER=`find app/server -name '*.js' | xargs jshint`
-if [ "$?" != "0" ]; then
-    printf '\033[1;31m \xe2\x9c\x98\n\033[0m'; # failed
-    echo
-    echo "output below:\n"
-    echo $ERRORS_ON_SERVER
-    exit 1
-else
-    printf '\033[1;32m \xe2\x9c\x94\n\033[0m'; # passed
-fi;
-
-printf 'Looking for errors on the terminal...'
-ERRORS_ON_TERMINAL=`find app/terminal -name '*.js' | xargs jshint`
-if [ "$?" != "0" ]; then
-    printf '\033[1;31m \xe2\x9c\x98\n\033[0m'; # failed
-    echo
-    echo "output below:\n"
-    echo $ERRORS_ON_TERMINAL
-    exit 1
-else
-    printf '\033[1;32m \xe2\x9c\x94\n\033[0m'; # passed
-fi;
+done;
